server:
  port: 8000

spring:
  application:
    name: gateway
  # 路由转发
  cloud:
    gateway:
      routes[0]:
        id: system
        uri: http://127.0.0.1:8001
        predicates[0]:
          name: Path
          args[0]: /system/**
      routes[1]:
        id: business
        uri: http://127.0.0.1:8002
        predicates[0]:
          name: Path
          args[0]: /business/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
