server:
  port: 8001
  servlet:
    context-path: /system

spring:
  application:
    name: system
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/course?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 1999114zzm

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# mybatis配置
mybatis:
  mapper-locations: classpath:/mapper/*.xml

# 查看操作数据库日志
logging:
  level:
    com:
      course:
        system:
          mapper: trace
